In [8]:
import numpy as np
my_list = [1,2,3]
my_array = np.array(my_list,dtype="uint16")
print(type(my_array))
print(my_array)
print(my_array.dtype)

<class 'numpy.ndarray'>
[1 2 3]
uint16


In [9]:
my_matrix = [[1,2,3],
             [4,5,6],
             [7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange

在給定的間隔內返回均勻間隔的值。[[參考資料](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [25]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [23]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [30]:
newArray = np.eye(5) * 6
print(newArray)

[[6. 0. 0. 0. 0.]
 [0. 6. 0. 0. 0.]
 [0. 0. 6. 0. 0.]
 [0. 0. 0. 6. 0.]
 [0. 0. 0. 0. 6.]]


## Random 
NumPy也有許多方法來創建隨機數陣列：

### rand
創建一個給定形狀的陣列，並用來自於[0, 1)的均勻分布的隨機樣本填充它。[[參考資料](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [38]:
np.random.rand(3)

array([0.17942075, 0.9187068 , 0.72155818])

In [40]:
np.random.rand(3,2)

array([[0.00974029, 0.15199356],
       [0.05430258, 0.35001187],
       [0.48726615, 0.7896724 ]])

### randn

從“標準正態”分佈[σ = 1]返回樣本（或樣本）。與 **rand** 不同，靠近零的值更有可能出現。[[參考資料](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]


標準正態分佈是一種特殊的常態分佈，其平均數（μ）為0，標準差（σ）為1。在標準正態分佈中，數據點主要集中在平均值附近，並且隨著距離平均值的增加而呈指數下降。這種分佈的曲線形狀呈鐘形，並且在平均值附近有一個尖峰。

在機器學習和統計學中，標準正態分佈通常用於建模和分析，並且在許多算法和技術中被廣泛應用。

In [41]:
np.random.randn(3)

array([-0.27358212,  0.43721384, -2.11429442])

In [42]:
np.random.randn(5,5)

array([[ 0.79705028,  0.89032271,  0.86560798, -1.68261158, -0.60716953],
       [ 1.07837826,  0.153029  ,  0.06556828, -0.84895464, -0.87845649],
       [-0.23054205,  0.67145511,  0.39765136, -0.60712617, -0.97380498],
       [ 1.07434472, -0.29167188, -0.25315033,  1.21346729,  0.97611934],
       [ 0.63293185, -1.00952628,  0.71599165,  0.15200828, -0.15547431]])

In [52]:
myData =  np.random.randn(1000000)
print("mean:",myData.mean())
print("std:",myData.std())

mean: -0.0008766318241236439
std: 1.0018626763810003


### randint
從`low`（包含）到`high`（不包含）返回隨機整數。 [[參考資料](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)]

In [122]:
np.random.randint(1,100,10)

array([13, 25, 91, 61, 22, 36,  7, 55, 76, 72])

In [116]:
#replace=False 加入了不重複抽
np.random.choice([5,8,2,6,5,9,10,20],2)

array([10, 20])

In [129]:
arr = np.arange(1,100)
print(arr)
np.random.shuffle(arr)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[ 4 15 82 98 75 93 40 28 76 94 52 20 24 27 47 12 18 91 50 44 90 37  7  9
 85 19 66 77 22  5 36 14 43 11 69 23 64  6 54 35 74 92 55 83  8 84 45 21
 51 38 62 58 63 26 99 42 49 13 31 32 67 72 57 80 39 79  3  1 71 60 33 17
 59 68 89 65 25 96 56 46 70 10 48 16 34 30 53 87 73 61 97 81 86 88 95 78
 41  2 29]


### seed
可以用來設置隨機狀態，以便可以重現相同的“隨機”結果。[[參考資料](https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html)]

In [145]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

## Reshape
返回一個包含相同數據但具有新形狀的陣列。[[參考資料](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)]

In [159]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[43 24 48 26 41 27 15 14 46 43]


In [148]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin


In [160]:
ranarr.max()

48

In [161]:
ranarr.argmax()#最大值的index

2

In [162]:
ranarr.min()

14

In [163]:
ranarr.argmin()#最小值的index

7

In [165]:
arr = np.arange(2,15)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [166]:
arr[3]

5

In [167]:
arr[1:5]

array([3, 4, 5, 6])

In [168]:
arr[:5]

array([2, 3, 4, 5, 6])

In [169]:
arr[-3:]

array([12, 13, 14])

In [ ]:
arr2 = np.arange(2,15)
arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [173]:
arr2[2:5] = 100
arr2

array([  2,   3, 100, 100, 100,   7,   8,   9,  10,  11,  12,  13,  14])

In [176]:
arr2[-3:] = [88,99,77]
arr2

array([  2,   3, 100, 100, 100,   7,   8,   9,  10,  11,  88,  99,  77])

In [177]:
myList = list(range(1,21))
myList

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [181]:
newList = myList[2:7]
newList[2] = 100
print(myList)
print(newList)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[3, 4, 100, 6, 7]


In [182]:
array4 = np.arange(1,21)
array4


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [183]:
newArray =  array4[2:7]
newArray

array([3, 4, 5, 6, 7])

In [184]:
newArray[2] = 99
print(array4)
print(newArray)

[ 1  2  3  4 99  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  4 99  6  7]


## 索引二維陣列（矩陣）

一般格式是 **arr_2d[row][col]** 或 **arr_2d[row, col]**。我推薦使用逗號標記法以增加清晰度。

In [188]:
arr_2d = np.array( ([5,10,15],
                    [20,25,30],
                    [35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [189]:
arr_2d[1]

array([20, 25, 30])

In [190]:
arr_2d[1][0]

20

In [192]:
arr_2d[2,1]

40

In [193]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [194]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

## 條件選擇

這是一個非常基礎的概念，稍後將直接應用於 pandas，請確保你理解這部分！

我們來簡要介紹如何使用括號進行基於比較運算符的選擇。

In [196]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [198]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])